pattern: LP
main: main/train.py
batchsize: 1024
epoch: 100
snapshot_interval: 1
experiment_iterations: 1
log_interval: 1
train_val_split_ratio: 0.99

models:
  pattern: CLIP-ViT-B-32
  classifier:
    func: model/lp_zcbm.py
    name: LpCLIP
    args:
      num_classes: 1000

dataset:
  dataset_func: data/generic.py
  dataset_name: ImageNet
  args:
    test: False

optimizer_c:
  algorithm: SGD
  lr_milestone: cosine
  args:
    lr: 0.1
    nesterov: True
    weight_decay: 1.0e-6
    momentum: 0.9
    
updater:
  func: updater/classification.py
  name: ClassifierUpdater